apiVersion: v1
kind: ConfigMap
metadata:
  name: mysql-initdb-config
data:
  init.sql: |
    CREATE DATABASE IF NOT EXISTS mydb;
    USE mydb;
    DROP TABLE IF EXISTS `todos`;
    CREATE TABLE IF NOT EXISTS `todos` (
      `id` int(10) UNSIGNED NOT NULL AUTO_INCREMENT,
      `todo` varchar(191) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
      `completed` varchar(191) COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT '0',
      `created_at` timestamp NULL DEFAULT NULL,
      `updated_at` timestamp NULL DEFAULT NULL,
      PRIMARY KEY (`id`)
    ) ENGINE=InnoDB AUTO_INCREMENT=42 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;