apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql-app
  labels:
    app: mysql-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mysql-app
  template:
    metadata:
      labels:
        app: mysql-app
    spec:
      containers:
      - name: mysql-app-ctr
        image: mysql:latest
        env:
          - name: MYSQL_DATABASE
            value: "mydb"
          - name: MYSQL_ROOT_PASSWORD
            valueFrom:
              secretKeyRef:
                name: mysql-secret
                key: MYSQL_ROOT_PASSWORD
          - name: MYSQL_USER
            value: "admin"
          - name: MYSQL_PASSWORD
            value: "admin"
        ports:
        - containerPort: 3306
        imagePullPolicy: Always
        volumeMounts:
          - name: mysql-initdb
            mountPath: docker-entrypoint-initdb.d

      volumes:
        - name: mysql-initdb
          configMap:
            name: mysql-initdb-config
