apiVersion: v1
kind: Service
metadata:
  name: phpmyadmin-svc
  labels:
    app: phpmyadmin-app
spec:
  selector:
    app: phpmyadmin-app
  ports:
    - protocol: TCP
      port: 8099       
      targetPort: 80
      nodePort: 30007  
  type: NodePort  