apiVersion: v1
kind: Service
metadata:
  name: todoapp-svc
  labels:
    app: todo-app
spec:
  selector:
    app: todo-app
  ports:
    - protocol: TCP
      port: 8088      
      targetPort: 80
      nodePort: 30008 
  type: NodePort  